# Generated by Django 5.1.3 on 2025-01-18 02:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
