# Generated by Django 5.1.3 on 2025-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_idea_idea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(upload_to='ideas/'),
        ),
    ]
