# Generated by Django 5.1.3 on 2025-01-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0003_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='image',
            field=models.ImageField(upload_to='FAQ/'),
        ),
    ]
