# Generated by Django 5.1.3 on 2025-01-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
